name: Process changes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  process-changes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build:spa
    - run: npm run test:badges
