name: Build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: install packages, test and build
      run: |
        npm install -g yarn
        npm install -g lerna
        yarn run ci
      env:
        CI: true
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "testAndBuild workflow"
        git commit -m "automated ci" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
